apiVersion: apps/v1
kind: Deployment
metadata:
  name: vbx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vbx
  template:
    metadata:
      labels:
        app: vbx
    spec:
      containers:
      - name: vbx-container
        image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/my-repository/vbx-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
