apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vbx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: vbx.imcc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vbx-service
            port:
              number: 80
